version: '2'
linters:
  default: all
  enable:
    - gomodguard_v2
    - wsl_v5
    - exhaustruct_v5
  disable:
    - exhaustruct
    - gomodguard
    - wsl
    - testpackage
  exclusions:
    paths:
      - node_modules
  settings:
    gocyclo:
      min-complexity: 27
    cyclop:
      max-complexity: 20
    lll:
      line-length: 200
    funlen:
      lines: 80
      statements: 45
    goconst:
      min-len: 8
      min-occurrences: 12
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    revive:
      rules:
        - name: package-comments
          disabled: true
    depguard:
      rules:
        main:
          files:
            - "$all"
          allow:
            - "os"
            - "fmt"
            - "slices"
            - "sync"
            - "time"
            - "encoding/json"
            - "strconv"
            - "strings"
            - "context"
            - "net/http"
            - "net/url"
            - "sort"
            - "path/filepath"
            - "testing"
            - "io"
            - "bytes"
            - "errors"
            - "github.com/grafana/grafana-plugin-sdk-go/"
            - "go.uber.org/zap"
            - "github.com/jsternberg/zap-logfmt"
            - "gopkg.in/natefinch/lumberjack.v2"
            - "github.com/ConSol-Monitoring/grafana-thruk-backend-datasource/pkg/plugin"
